name = "Decay Chain"
author = "AlexCatze"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0441f9edcd3ec4318a80990505b1d54f4b77c3875bede50c234522062722c93"

[versions]
forge = "14.23.5.2864"
minecraft = "1.12.2"
