name = "Decay Chain"
author = "AlexCatze"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e5f778240e00e2a2191d18fa3b36c414ea5d2fcf7cea92391d776df4f8b3946"

[versions]
forge = "14.23.5.2864"
minecraft = "1.12.2"
